using Microsoft.EntityFrameworkCore.Design;

namespace MeetingTranscriber.Infrastructure.Storage;

/// <summary>
/// What `dotnet ef migrations add` builds its model from. The folder is a throwaway: migrations
/// are generated by diffing the model, and nothing is ever run against a real corpus here.
/// </summary>
public sealed class CorpusDbContextFactory : IDesignTimeDbContextFactory<CorpusDbContext>
{
    public CorpusDbContext CreateDbContext(string[] args) =>
        new(CorpusDatabase.OptionsFor(
            new DirectoryInfo(Path.Combine(Path.GetTempPath(), "meeting-transcriber-design"))));
}
