// <auto-generated />
using System;
using MeetingTranscriber.Infrastructure.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingTranscriber.Infrastructure.Migrations
{
    [DbContext(typeof(CorpusDbContext))]
    [Migration("20260816220840_OpenQuestionsAndDecisionPositions")]
    partial class OpenQuestionsAndDecisionPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MeetingTranscriber.Domain.Artifacts.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_size");

                    b.Property<string>("ConfirmedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.HasKey("Id")
                        .HasName("pk_artifacts");

                    b.HasIndex("Origin")
                        .HasDatabaseName("ix_artifacts_origin");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_artifacts_sha256");

                    b.HasIndex("MeetingId", "RelativePath")
                        .IsUnique()
                        .HasDatabaseName("ix_artifacts_meeting_id_relative_path");

                    b.ToTable("artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_artifacts_byte_size", "byte_size >= 0");

                            t.HasCheckConstraint("ck_artifacts_origin", "(origin = 'source' AND kind IN ('audio', 'deepgram_response', 'extraction', 'manifest', 'spool_block')) OR (origin = 'derived' AND kind IN ('summary', 'transcript', 'utterances'))");

                            t.HasCheckConstraint("ck_artifacts_sha256", "length(sha256) = 64");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.CaptureRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BitsPerSample")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bits_per_sample");

                    b.Property<int>("ChannelCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_count");

                    b.Property<long?>("Drift")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drift_ms");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("MeDeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("me_device_id");

                    b.Property<string>("MeDeviceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("me_device_name");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<string>("OthersCaptureMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("others_capture_mode");

                    b.Property<string>("OthersDeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("others_device_id");

                    b.Property<string>("OthersDeviceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("others_device_name");

                    b.Property<string>("OthersProcess")
                        .HasColumnType("TEXT")
                        .HasColumnName("others_process");

                    b.Property<bool>("Recovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recovered");

                    b.Property<int>("SampleRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sample_rate");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_capture_runs");

                    b.HasIndex("MeetingId", "StartedAt")
                        .HasDatabaseName("ix_capture_runs_meeting_id_started_at");

                    b.ToTable("capture_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_capture_runs_others_capture_mode", "others_capture_mode IN ('full_loopback', 'process_loopback')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.ExtractionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("input_hash");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<Guid?>("OutputArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_artifact_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_version");

                    b.Property<string>("RawOutputHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_output_hash");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_extraction_runs");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_extraction_runs_job_id");

                    b.HasIndex("OutputArtifactId")
                        .HasDatabaseName("ix_extraction_runs_output_artifact_id");

                    b.HasIndex("MeetingId", "CreatedAt")
                        .HasDatabaseName("ix_extraction_runs_meeting_id_created_at");

                    b.ToTable("extraction_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_extraction_runs_input_hash", "length(input_hash) = 64");

                            t.HasCheckConstraint("ck_extraction_runs_raw_output_hash", "raw_output_hash IS NULL OR length(raw_output_hash) = 64");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<string>("AwaitingReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("awaiting_reason");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<string>("NextAttemptAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_processing_jobs");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_processing_jobs_meeting_id");

                    b.HasIndex("Kind", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_processing_jobs_kind_idempotency_key");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_processing_jobs_state_next_attempt_at");

                    b.ToTable("processing_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_processing_jobs_attempt", "attempt >= 0");

                            t.HasCheckConstraint("ck_processing_jobs_awaiting_reason", "(state = 'awaiting_user') = (awaiting_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_processing_jobs_kind", "kind IN ('backup', 'capture', 'extract', 'finalize', 'render', 'transcribe')");

                            t.HasCheckConstraint("ck_processing_jobs_state", "state IN ('awaiting_user', 'cancelled', 'failed_permanent', 'failed_retryable', 'pending', 'running', 'succeeded')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.TranscriptionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApprovedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("approved_at");

                    b.Property<string>("AudioSha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_sha256");

                    b.Property<string>("BillableConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("billable_config_hash");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<long?>("EstimatedCostMicros")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estimated_cost_micros");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("PriceTableVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_table_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<Guid?>("ResponseArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_artifact_id");

                    b.Property<string>("SourceProfile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_profile");

                    b.HasKey("Id")
                        .HasName("pk_transcription_runs");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_transcription_runs_job_id");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_transcription_runs_meeting_id");

                    b.HasIndex("ResponseArtifactId")
                        .HasDatabaseName("ix_transcription_runs_response_artifact_id");

                    b.HasIndex("AudioSha256", "BillableConfigHash")
                        .HasDatabaseName("ix_transcription_runs_audio_sha256_billable_config_hash");

                    b.ToTable("transcription_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_transcription_runs_audio_sha256", "length(audio_sha256) = 64");

                            t.HasCheckConstraint("ck_transcription_runs_cost", "estimated_cost_micros IS NULL OR estimated_cost_micros >= 0");

                            t.HasCheckConstraint("ck_transcription_runs_source_profile", "source_profile IN ('diarize', 'multichannel')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ExtractionRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_run_id");

                    b.Property<Guid>("MeetingId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("statement");

                    b.HasKey("Id")
                        .HasName("pk_action_items");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_action_items_due_date");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_action_items_meeting_id");

                    b.HasIndex("ExtractionRunId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_action_items_extraction_run_id_ordinal");

                    b.ToTable("action_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_action_items_evidence_span", "start_ms >= 0 AND end_ms >= start_ms");

                            t.HasCheckConstraint("ck_action_items_ordinal", "ordinal >= 0");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DecidedByPersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_by_person_id");

                    b.Property<Guid>("ExtractionRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_run_id");

                    b.Property<Guid>("MeetingId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("statement");

                    b.HasKey("Id")
                        .HasName("pk_decisions");

                    b.HasIndex("DecidedByPersonId")
                        .HasDatabaseName("ix_decisions_decided_by_person_id");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_decisions_meeting_id");

                    b.HasIndex("ExtractionRunId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_decisions_extraction_run_id_ordinal");

                    b.ToTable("decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_decisions_evidence_span", "start_ms >= 0 AND end_ms >= start_ms");

                            t.HasCheckConstraint("ck_decisions_ordinal", "ordinal >= 0");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.OpenQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExtractionRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_run_id");

                    b.Property<Guid>("MeetingId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("pk_open_questions");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_open_questions_meeting_id");

                    b.HasIndex("ExtractionRunId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_open_questions_extraction_run_id_ordinal");

                    b.ToTable("open_questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_open_questions_evidence_span", "start_ms >= 0 AND end_ms >= start_ms");

                            t.HasCheckConstraint("ck_open_questions_ordinal", "ordinal >= 0");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("TEXT")
                        .HasColumnName("abstract");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExtractionRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_run_id");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.HasKey("Id")
                        .HasName("pk_summaries");

                    b.HasIndex("ExtractionRunId")
                        .HasDatabaseName("ix_summaries_extraction_run_id");

                    b.HasIndex("MeetingId", "ExtractionRunId")
                        .IsUnique()
                        .HasDatabaseName("ix_summaries_meeting_id_extraction_run_id");

                    b.ToTable("summaries", (string)null);
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.Utterance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("Channel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<long>("End")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_ms");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("SpeakerLabel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("speaker_label");

                    b.Property<long>("Start")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_ms");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_utterances");

                    b.HasAlternateKey("MeetingId", "Ordinal")
                        .HasName("ak_utterances_meeting_id_ordinal");

                    b.HasIndex("MeetingId", "Start")
                        .HasDatabaseName("ix_utterances_meeting_id_start_ms");

                    b.ToTable("utterances", null, t =>
                        {
                            t.HasCheckConstraint("ck_utterances_channel", "channel IS NULL OR channel IN (0, 1)");

                            t.HasCheckConstraint("ck_utterances_confidence", "confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)");

                            t.HasCheckConstraint("ck_utterances_ordinal", "ordinal >= 0");

                            t.HasCheckConstraint("ck_utterances_span", "start_ms >= 0 AND end_ms >= start_ms");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.ActionItemProgress", b =>
                {
                    b.Property<Guid>("ExtractionRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_run_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_person_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ExtractionRunId", "Ordinal")
                        .HasName("pk_action_item_progress");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("ix_action_item_progress_owner_person_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_action_item_progress_state");

                    b.ToTable("action_item_progress", null, t =>
                        {
                            t.HasCheckConstraint("ck_action_item_progress_ordinal", "ordinal >= 0");

                            t.HasCheckConstraint("ck_action_item_progress_state", "state IN ('done', 'dropped', 'open')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Affiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_id");

                    b.Property<string>("OrganizationKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_kind");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("person_id");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_affiliations");

                    b.HasIndex("OrganizationId", "OrganizationKind")
                        .HasDatabaseName("ix_affiliations_organization_id_organization_kind");

                    b.HasIndex("PersonId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_affiliations_person_id_organization_id")
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("affiliations", null, t =>
                        {
                            t.HasCheckConstraint("ck_affiliations_organization", "organization_kind = 'organization'");

                            t.HasCheckConstraint("ck_affiliations_period", "started_at IS NULL OR ended_at IS NULL OR ended_at >= started_at");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_audit_events_meeting_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_actor", "actor IN ('agent', 'app', 'user')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT")
                        .HasColumnName("context");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("SourceProfile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_profile");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_meetings");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_meetings_started_at");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_meetings_template_id");

                    b.HasIndex("LifecycleState", "StartedAt")
                        .HasDatabaseName("ix_meetings_lifecycle_state_started_at");

                    b.ToTable("meetings", null, t =>
                        {
                            t.HasCheckConstraint("ck_meetings_deleted_at", "(lifecycle_state = 'active') = (deleted_at IS NULL)");

                            t.HasCheckConstraint("ck_meetings_duration", "duration_ms IS NULL OR duration_ms >= 0");

                            t.HasCheckConstraint("ck_meetings_lifecycle_state", "lifecycle_state IN ('active', 'deleted', 'deleting')");

                            t.HasCheckConstraint("ck_meetings_source_profile", "source_profile IN ('diarize', 'multichannel')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.MeetingNode", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("MeetingId", "NodeId", "Role")
                        .HasName("pk_meeting_nodes");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_meeting_nodes_node_id");

                    b.ToTable("meeting_nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_meeting_nodes_role", "role IN ('about', 'counterpart', 'work_of')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.MeetingPerson", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("MeetingId", "PersonId", "Role")
                        .HasName("pk_meeting_people");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_meeting_people_person_id");

                    b.ToTable("meeting_people", null, t =>
                        {
                            t.HasCheckConstraint("ck_meeting_people_role", "role IN ('attended', 'subject')");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.MeetingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_templates_name");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParentDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_depth");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentKind")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_kind");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasAlternateKey("Id", "Kind")
                        .HasName("ak_nodes_id_kind");

                    b.HasAlternateKey("Id", "Kind", "Depth")
                        .HasName("ak_nodes_id_kind_depth");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_nodes_name")
                        .HasFilter("parent_id IS NULL");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_nodes_parent_id_name");

                    b.HasIndex("ParentId", "ParentKind", "ParentDepth")
                        .HasDatabaseName("ix_nodes_parent_id_parent_kind_parent_depth");

                    b.ToTable("nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_nodes_child_depth", "parent_depth IS NULL OR depth = parent_depth + 1");

                            t.HasCheckConstraint("ck_nodes_depth", "depth BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_nodes_kind", "kind IN ('initiative', 'organization', 'topic')");

                            t.HasCheckConstraint("ck_nodes_parent", "(parent_id IS NULL) = (parent_kind IS NULL) AND (parent_id IS NULL) = (parent_depth IS NULL)");

                            t.HasCheckConstraint("ck_nodes_parent_kind", "(parent_kind IS NULL AND kind IN ('organization', 'initiative')) OR (parent_kind IS 'organization' AND kind = 'initiative') OR (parent_kind IS 'initiative' AND kind = 'topic')");

                            t.HasCheckConstraint("ck_nodes_root", "(parent_id IS NULL) = (depth = 0)");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsMe")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_me");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.SpeakerAssignment", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<string>("SpeakerLabel")
                        .HasColumnType("TEXT")
                        .HasColumnName("speaker_label");

                    b.Property<string>("AssignedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("person_id");

                    b.HasKey("MeetingId", "SpeakerLabel")
                        .HasName("pk_speaker_assignments");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_speaker_assignments_person_id");

                    b.ToTable("speaker_assignments", (string)null);
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.TerminologyCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CorrectText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correct_text");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("match_mode");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("meeting_id");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<string>("WrongText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("wrong_text");

                    b.HasKey("Id")
                        .HasName("pk_terminology_corrections");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_terminology_corrections_meeting_id");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_terminology_corrections_node_id");

                    b.ToTable("terminology_corrections", null, t =>
                        {
                            t.HasCheckConstraint("ck_terminology_corrections_scope", "node_id IS NULL OR meeting_id IS NULL");
                        });
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Artifacts.Artifact", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artifacts_meetings_meeting_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.CaptureRun", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capture_runs_meetings_meeting_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.ExtractionRun", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Jobs.ProcessingJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_runs_processing_jobs_job_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_runs_meetings_meeting_id");

                    b.HasOne("MeetingTranscriber.Domain.Artifacts.Artifact", null)
                        .WithMany()
                        .HasForeignKey("OutputArtifactId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_extraction_runs_artifacts_output_artifact_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.ProcessingJob", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processing_jobs_meetings_meeting_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Jobs.TranscriptionRun", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Jobs.ProcessingJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_transcription_runs_processing_jobs_job_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transcription_runs_meetings_meeting_id");

                    b.HasOne("MeetingTranscriber.Domain.Artifacts.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ResponseArtifactId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transcription_runs_artifacts_response_artifact_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.ActionItem", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Jobs.ExtractionRun", null)
                        .WithMany()
                        .HasForeignKey("ExtractionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_items_extraction_runs_extraction_run_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_items_meetings_meeting_id");

                    b.OwnsOne("MeetingTranscriber.Domain.Knowledge.Citation", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("ActionItemId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("End")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_ms");

                            b1.Property<Guid>("MeetingId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("meeting_id");

                            b1.Property<string>("QuotedText")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("quoted_text");

                            b1.Property<string>("SourceArtifactSha256")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("source_artifact_sha256");

                            b1.Property<string>("SpeakerLabel")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("speaker_label");

                            b1.Property<long>("Start")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_ms");

                            b1.Property<int>("UtteranceOrdinal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("utterance_ordinal");

                            b1.HasKey("ActionItemId")
                                .HasName("pk_action_items");

                            b1.HasIndex("MeetingId", "UtteranceOrdinal")
                                .HasDatabaseName("ix_action_items_meeting_id_utterance_ordinal");

                            b1.ToTable("action_items");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId")
                                .HasConstraintName("fk_action_items_action_items_actionitemid");

                            b1.HasOne("MeetingTranscriber.Domain.Knowledge.Utterance", null)
                                .WithMany()
                                .HasForeignKey("MeetingId", "UtteranceOrdinal")
                                .HasPrincipalKey("MeetingId", "Ordinal")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("fk_action_items_utterances_meeting_id_utterance_ordinal");
                        });

                    b.Navigation("Evidence")
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.Decision", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Person", null)
                        .WithMany()
                        .HasForeignKey("DecidedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_decisions_people_decided_by_person_id");

                    b.HasOne("MeetingTranscriber.Domain.Jobs.ExtractionRun", null)
                        .WithMany()
                        .HasForeignKey("ExtractionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decisions_extraction_runs_extraction_run_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decisions_meetings_meeting_id");

                    b.OwnsOne("MeetingTranscriber.Domain.Knowledge.Citation", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("DecisionId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("End")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_ms");

                            b1.Property<Guid>("MeetingId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("meeting_id");

                            b1.Property<string>("QuotedText")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("quoted_text");

                            b1.Property<string>("SourceArtifactSha256")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("source_artifact_sha256");

                            b1.Property<string>("SpeakerLabel")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("speaker_label");

                            b1.Property<long>("Start")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_ms");

                            b1.Property<int>("UtteranceOrdinal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("utterance_ordinal");

                            b1.HasKey("DecisionId")
                                .HasName("pk_decisions");

                            b1.HasIndex("MeetingId", "UtteranceOrdinal")
                                .HasDatabaseName("ix_decisions_meeting_id_utterance_ordinal");

                            b1.ToTable("decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionId")
                                .HasConstraintName("fk_decisions_decisions_decisionid");

                            b1.HasOne("MeetingTranscriber.Domain.Knowledge.Utterance", null)
                                .WithMany()
                                .HasForeignKey("MeetingId", "UtteranceOrdinal")
                                .HasPrincipalKey("MeetingId", "Ordinal")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("fk_decisions_utterances_meeting_id_utterance_ordinal");
                        });

                    b.Navigation("Evidence")
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.OpenQuestion", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Jobs.ExtractionRun", null)
                        .WithMany()
                        .HasForeignKey("ExtractionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_open_questions_extraction_runs_extraction_run_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_open_questions_meetings_meeting_id");

                    b.OwnsOne("MeetingTranscriber.Domain.Knowledge.Citation", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("OpenQuestionId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("End")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_ms");

                            b1.Property<Guid>("MeetingId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("meeting_id");

                            b1.Property<string>("QuotedText")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("quoted_text");

                            b1.Property<string>("SourceArtifactSha256")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("source_artifact_sha256");

                            b1.Property<string>("SpeakerLabel")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("speaker_label");

                            b1.Property<long>("Start")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_ms");

                            b1.Property<int>("UtteranceOrdinal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("utterance_ordinal");

                            b1.HasKey("OpenQuestionId")
                                .HasName("pk_open_questions");

                            b1.HasIndex("MeetingId", "UtteranceOrdinal")
                                .HasDatabaseName("ix_open_questions_meeting_id_utterance_ordinal");

                            b1.ToTable("open_questions");

                            b1.WithOwner()
                                .HasForeignKey("OpenQuestionId")
                                .HasConstraintName("fk_open_questions_open_questions_openquestionid");

                            b1.HasOne("MeetingTranscriber.Domain.Knowledge.Utterance", null)
                                .WithMany()
                                .HasForeignKey("MeetingId", "UtteranceOrdinal")
                                .HasPrincipalKey("MeetingId", "Ordinal")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("fk_open_questions_utterances_meeting_id_utterance_ordinal");
                        });

                    b.Navigation("Evidence")
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.Summary", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Jobs.ExtractionRun", null)
                        .WithMany()
                        .HasForeignKey("ExtractionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_extraction_runs_extraction_run_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_meetings_meeting_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Knowledge.Utterance", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_utterances_meetings_meeting_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.ActionItemProgress", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Jobs.ExtractionRun", null)
                        .WithMany()
                        .HasForeignKey("ExtractionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_item_progress_extraction_runs_extraction_run_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Person", null)
                        .WithMany()
                        .HasForeignKey("OwnerPersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_action_item_progress_people_owner_person_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Affiliation", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_affiliations_people_person_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Node", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OrganizationKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_affiliations_nodes_organization_id_organization_kind");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.AuditEvent", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_events_meetings_meeting_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Meeting", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.MeetingTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_meetings_templates_template_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.MeetingNode", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meeting_nodes_meetings_meeting_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meeting_nodes_nodes_node_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.MeetingPerson", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meeting_people_meetings_meeting_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meeting_people_people_person_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.Node", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Node", null)
                        .WithMany()
                        .HasForeignKey("ParentId", "ParentKind", "ParentDepth")
                        .HasPrincipalKey("Id", "Kind", "Depth")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_nodes_nodes_parent_id_parent_kind_parent_depth");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.SpeakerAssignment", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_speaker_assignments_meetings_meeting_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_speaker_assignments_people_person_id");
                });

            modelBuilder.Entity("MeetingTranscriber.Domain.Meetings.TerminologyCorrection", b =>
                {
                    b.HasOne("MeetingTranscriber.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_terminology_corrections_meetings_meeting_id");

                    b.HasOne("MeetingTranscriber.Domain.Meetings.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_terminology_corrections_nodes_node_id");
                });
#pragma warning restore 612, 618
        }
    }
}
